#logging:
#  level:
#    org.springframework.mail: DEBUG
#    org.springframework.web: DEBUG
#    org.apache.http: DEBUG
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8096
  error:
    whitelabel.enabled: false
    path: /error
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bonus_qt
    username: admin_bonus
    password: T-6917111t
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  messages:
    encoding: UTF-8
  mail:
    host: smtp.yandex.ru
    port: 465
    username: wtorushin@yandex.ru
    password: asakuebskebobmmt
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false  # Отключаем, так как SSL на порту 465 уже достаточно