logging:
  level:
    org.springframework.mail: ERROR
    org.springframework.web: ERROR
    org.apache.http: ERROR
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8096
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  servlet:
    multipart:
      location: C:\\bonus\\app\\permanent\\uploads  # Указываем путь к временной директории
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    primary:
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:bonus_qt}
      username: admin_bonus
      password: T-6917111t
      driver-class-name: org.postgresql.Driver
    crm:
      url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:db_qt_crm}
      username: qt_user
      password: qt_user
      driver-class-name: org.postgresql.Driver
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:C:/bonus/app/images/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  messages:
    encoding: UTF-8
    basename: messages
  locale: ru
  mail:
    host: smtp.yandex.ru
    port: 465
    username: bonus@quartztop.ru
    password: zbegnwpgrrgwmuqh
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false  # Отключаем, так как SSL на порту 465 уже достаточно